apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thanos-app-notif
generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yml
- ../bases
- ../envs

patches:
- path: resource_override.yml
