apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-app-notif
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thanos-app-notif
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: thanos-app-notif
          image: thanos-app-notif:latest
          imagePullPolicy: Never
          command: ["thanos-app-notif"]
          args: ["listener"] 

      
       