apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yml
- service.yml

labels:
- includeSelectors: true
  pairs:
    app: thanos-app-notif
